dept_cfg = {
    'INFO':10,
    'QK':10,
    'EK':10,
    'NKAC':10,
    'CRAC':10,
    'WKAB':10,
    'WKAC':10,
    'NKAA':10,
    'JZ':10,
    'NKAB':10,
    'YK':10,
    'WKAA':10,
    'WKAG':10,
    'JS':10,
    'EKAB':10,
    'PFAB':10,
    'NKAL':10,
    'NKAJ':10,
    'NKAM':10,
    'NKAD':10,
    'WKAH':10,
    'NKAE':10,
    'WKAR':10,
    'JY':10,
    'WKAT':10,
    'ZZ':10,
    'SJ':10,
    'NKAF':10
}
dept_all = {
    'CR':'CR,CRAA',
    'EK':'EK,EKAA',
    'PF':'PF,PFAA',
    'YX':'YX,YXAD',
    'CRAA':'CR,CRAA',
    'EKAA':'EK,EKAA',
    'PFAA':'PF,PFAA',
    'YXAD':'YX,YXAD',
}


